# Generated by Django 3.0.5 on 2020-04-09 23:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NovelEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False, verbose_name='UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('gmt_modified', models.DateTimeField(auto_now=True, verbose_name='上次修改时间')),
                ('ip_addr', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('name', models.CharField(max_length=50, verbose_name='小说名字')),
                ('url', models.CharField(max_length=255, verbose_name='小说网站url')),
                ('host', models.CharField(max_length=255, verbose_name='小说网站host')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SectionContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False, verbose_name='UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('gmt_modified', models.DateTimeField(auto_now=True, verbose_name='上次修改时间')),
                ('ip_addr', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('content', models.TextField(verbose_name='章节下的主要内容')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.NovelEntry', verbose_name='小说章节')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NovelSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False, verbose_name='UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('gmt_modified', models.DateTimeField(auto_now=True, verbose_name='上次修改时间')),
                ('ip_addr', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('name', models.CharField(max_length=50, verbose_name='章节名')),
                ('url', models.CharField(max_length=255, verbose_name='章节url')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.NovelEntry', verbose_name='小说')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
