# Generated by Django 3.0.5 on 2020-04-10 00:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0002_novelsection_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraspRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False, verbose_name='UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('gmt_modified', models.DateTimeField(auto_now=True, verbose_name='上次修改时间')),
                ('ip_addr', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('service', models.CharField(max_length=50, null=True, verbose_name='网站服务地址')),
                ('host', models.CharField(max_length=100, verbose_name='网站host')),
                ('section_rule', models.CharField(max_length=100, verbose_name='章节抓取规则')),
                ('content', models.CharField(max_length=100, verbose_name='内容抓取规则')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
