# Generated by Django 3.0.5 on 2020-04-10 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0003_grasprule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grasprule',
            old_name='content',
            new_name='content_rule',
        ),
    ]
