# Generated by Django 3.0.5 on 2020-04-10 00:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0004_auto_20200410_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='grasprule',
            name='section_rule_p',
            field=models.CharField(max_length=100, verbose_name='父类章节抓取规则'),
            preserve_default=False,
        ),
    ]
