# Generated by Django 3.0.5 on 2020-04-10 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0005_grasprule_section_rule_p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grasprule',
            name='section_rule_p',
            field=models.CharField(max_length=100, null=True, verbose_name='父类章节抓取规则'),
        ),
    ]
