# Generated by Django 2.0.6 on 2020-04-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0006_auto_20200410_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='grasprule',
            name='list_rule',
            field=models.CharField(max_length=100, verbose_name='列表抓取规则'),
            preserve_default=False,
        ),
    ]
