# Generated by Django 2.0.6 on 2020-04-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0007_grasprule_list_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novelsection',
            name='url',
            field=models.CharField(max_length=255, null=True, verbose_name='章节url'),
        ),
    ]
