# Generated by Django 2.0.6 on 2020-04-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0008_auto_20200410_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novelsection',
            name='name',
            field=models.CharField(max_length=255, verbose_name='章节名'),
        ),
    ]
