# Generated by Django 2.0.6 on 2020-04-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0009_auto_20200410_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='novelsection',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='序号'),
        ),
    ]
