# Generated by Django 3.0.5 on 2020-04-11 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0010_novelsection_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='grasprule',
            name='decode',
            field=models.CharField(default='utf-8', max_length=20, verbose_name='解码配置'),
        ),
    ]
