# Generated by Django 3.0.5 on 2020-04-12 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0011_grasprule_decode'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectioncontent',
            name='novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_novel', to='novel.NovelEntry', verbose_name='小说'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='novelsection',
            name='novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_novel', to='novel.NovelEntry', verbose_name='小说'),
        ),
    ]
