# Generated by Django 3.0.5 on 2020-04-12 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0012_auto_20200412_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectioncontent',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.NovelSection', verbose_name='小说章节'),
        ),
    ]
