# Generated by Django 3.0.5 on 2020-05-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0013_auto_20200412_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='grasprule',
            name='book_name',
            field=models.CharField(max_length=20, null=True, verbose_name='书名规则'),
        ),
    ]
