# Generated by Django 3.0.5 on 2020-05-05 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0014_grasprule_book_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grasprule',
            name='book_name',
            field=models.CharField(max_length=100, null=True, verbose_name='书名规则'),
        ),
    ]
