# Generated by Django 3.0.5 on 2020-05-05 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0015_auto_20200505_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novelentry',
            name='host',
        ),
    ]
