# Generated by Django 3.0.5 on 2020-05-05 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0016_remove_novelentry_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='novelentry',
            name='section_complete',
            field=models.BooleanField(default=False, verbose_name='章节是否已经获取'),
        ),
    ]
