# Generated by Django 3.0.5 on 2020-05-05 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0017_novelentry_section_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='novelentry',
            name='content_complete',
            field=models.BooleanField(default=False, verbose_name='内容是否已经获取'),
        ),
    ]
