# Generated by Django 3.0.5 on 2020-06-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0020_novelentry_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grasprule',
            name='service',
            field=models.CharField(max_length=255, null=True, verbose_name='网站服务地址'),
        ),
    ]
