# Generated by Django 2.2.7 on 2019-11-22 12:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False, verbose_name='UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('gmt_modified', models.DateTimeField(auto_now=True, verbose_name='上次修改时间')),
                ('ip_addr', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('url', models.CharField(max_length=1000, verbose_name='url')),
                ('type_name', models.CharField(max_length=32, verbose_name='类型名')),
                ('type_code', models.CharField(max_length=36, verbose_name='类型code')),
                ('mark', models.CharField(max_length=255, verbose_name='备注')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
