# Generated by Django 2.2.7 on 2019-11-22 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businfo',
            name='code',
            field=models.CharField(max_length=32, verbose_name='公交辨识码'),
            preserve_default=False,
        ),
    ]
