# Generated by Django 2.2.7 on 2019-11-22 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0002_businfo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='businfo',
            name='bus_type',
            field=models.CharField(max_length=32, verbose_name='公交所属区域'),
            preserve_default=False,
        ),
    ]
