# Generated by Django 2.2.7 on 2019-11-22 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_businfo_code'),
    ]

    operations = [

    ]
