# Generated by Django 2.2.7 on 2019-11-24 15:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0003_businfo_bus_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusTypeArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False, verbose_name='UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('gmt_modified', models.DateTimeField(auto_now=True, verbose_name='上次修改时间')),
                ('ip_addr', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('name', models.CharField(max_length=32, verbose_name='类型名')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
