# Generated by Django 2.0.6 on 2020-04-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0005_businfo_bus_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='businfo',
            name='grab_real_url',
            field=models.CharField(max_length=255, verbose_name='用来获取实况信息的url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businfo',
            name='real_url',
            field=models.CharField(max_length=255, null=True, verbose_name='获取实况信息的url'),
        ),
    ]
