# Generated by Django 2.0.6 on 2020-04-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0006_auto_20200413_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businfo',
            name='code',
            field=models.CharField(max_length=32, null=True, verbose_name='公交辨识码'),
        ),
        migrations.AlterField(
            model_name='businfo',
            name='departure_station',
            field=models.CharField(max_length=255, null=True, verbose_name='始发站'),
        ),
        migrations.AlterField(
            model_name='businfo',
            name='destination',
            field=models.CharField(max_length=255, null=True, verbose_name='终点站'),
        ),
    ]
