# Generated by Django 3.0.5 on 2020-04-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0007_auto_20200413_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='businfo',
            name='has_stations',
            field=models.BooleanField(default=False, verbose_name='是否已经存在站点信息'),
        ),
        migrations.AddField(
            model_name='businfo',
            name='update_time',
            field=models.DateField(null=True, verbose_name='更新站点信息的时间'),
        ),
    ]
