# Generated by Django 2.0.6 on 2020-04-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0008_auto_20200413_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='busstations',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='站点排序'),
        ),
    ]
