# Generated by Django 2.0.1 on 2018-03-26 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlogFront', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_info_num', models.CharField(max_length=150)),
                ('note_info_sign', models.IntegerField()),
                ('note_info_title', models.CharField(default=None, max_length=100)),
                ('note_info_code', models.TextField()),
                ('note_info_img', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NoteName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='笔记本名')),
                ('creat_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '笔记本',
            },
        ),
        migrations.CreateModel(
            name='NoteT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_num', models.CharField(max_length=150)),
                ('note_user', models.CharField(default=None, max_length=255)),
                ('creat_time', models.DateTimeField(auto_now_add=True)),
                ('note_title', models.CharField(default=None, max_length=255)),
                ('note_label', models.CharField(default=None, max_length=20)),
                ('belong', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='belong_name', to='BlogFront.NoteName')),
            ],
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
